# -*- coding: utf-8 -*-
"""CV3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCbLmo6idQMv_cjiFTDIdQEu64fXcvJH
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparision(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))

  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('original Grayscale image')
  plt.axis('off')

  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('3x3 kernal')
  plt.axis('off')

  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('5x5 Kernal')
  plt.axis('off')

  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('7x7 Kernal')
  plt.axis('off')

  plt.show()

from google.colab import drive
drive.mount('/content/drive')

img=cv2.imread('/content/drive/MyDrive/CV/download.jpg',0)
if img is None:
  print("error:image not found.")
else:
  kernel_3x3=np.ones((3,3),dtype=np.float32)/9.0
  kernel_5x5=np.ones((5,5),dtype=np.float32)/25.0
  kernel_7x7=np.ones((7,7),dtype=np.float32)/49.0

  blur_3x3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5x5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7x7=cv2.filter2D(img,-1,kernel_7x7)

  show_comparision(img,blur_3x3,blur_5x5,blur_7x7)

img=cv2.imread('/content/drive/MyDrive/CV/images.jpg',0)
if img is None:
  print("error:image not found.")
else:
  kernel_3x3=np.ones((3,3),dtype=np.float32)/9.0
  kernel_5x5=np.ones((5,5),dtype=np.float32)/25.0
  kernel_7x7=np.ones((7,7),dtype=np.float32)/49.0

  blur_3x3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5x5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7x7=cv2.filter2D(img,-1,kernel_7x7)

  show_comparision(img,blur_3x3,blur_5x5,blur_7x7)

import numpy as np
import matplotlib.pyplot as plt
image_np = np.array(img)
kernel = np.ones((11, 11)) / 121

k_s = 11

rows, cols = image_np.shape
output_rows = rows - k_s + 1
output_cols = cols - k_s + 1

filtered_img = np.zeros((output_rows, output_cols))

for i in range(output_rows):
    for j in range(output_cols):
        image_window = image_np[i : i + k_s, j : j + k_s]

        filtered_img[i, j] = np.sum(image_window * kernel)

print("Filtered Image (NumPy):")
print(filtered_img)
plt.imshow(filtered_img, cmap='gray')
plt.title('Filtered Image')
plt.axis('off')
plt.show()